### ISSUE TITLE
Add example code for `show()` modifications as per #2

### ISSUE THREAD

**Issue by samveen** [samveen/pico-oled-1.3-driver#5]
Need to add examples for the the newly updated `show()` function, as modified by #2

**Comment by joostit** [comment]
I might add this while I'm making changes for #8

How about implementing the `test()` method with simple example code?

**Comment by samveen** [comment]
Another item on the TODO. you have something to fill in there?

**Comment by joostit** [comment]
During development, I personally prefer to always have code that continuously validates the functionality of what I make. It serves both as functional tests during development, and as reference/example code for my users afterwards.

Is it an option to add a new Python script to the repo that contains that code, like `DisplayDemo.py`? 
(instead of only having the __main__ reference a test() method?)

**Comment by samveen** [comment]
I'll see what I can figure out for this.

**Comment by joostit** [comment]
I'll add this type of example code to my Fork soon. Feel free to cherry pick :)
